version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: python3 main.py
      - run: echo "Build completed successfully!"
      - run: echo "This is a sample CircleCI configuration file."

workflows:
  build_now:
    jobs:
      - build